baseURL = "http://kadudutra.dev/"
languageCode = "pt-br"
title = "Kadu Dutra"
theme = "m10c"
[[params.social]]
  name = "github"
  url = "https://github.com/kadudutra"
[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/kadudutra"
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/kadudutra"

[params.style]
    darkestColor = "#463625"
    darkColor = "#2a3738"
    primaryColor = "#eeee6a"
    lightColor = "#96a879"
    lightestColor = "#ffffff"
